language: php
cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"
php:
  - 5.5

sudo: false

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

install:
  # Add Composer's local bin directory to the PATH so that we will be running
  # our installed versions of Drush, PHPCS, Behat, PhantomJS, etc.
  - export PATH="$TRAVIS_BUILD_DIR/bin:$PATH"

  # MySQL Options
  - mysql -e 'SET GLOBAL wait_timeout = 5400;'
  - mysql -e "SHOW VARIABLES LIKE 'wait_timeout'"

  # PHP conf tweaks
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash

  # Let Composer do all the magic!
  - composer install

  # Install Lightning.
  - cd docroot
  - drush site-install lightning -y --account-pass=admin --db-url=mysql://root:@localhost/lpdf

before_script:
  - drush runserver --default-server=builtin 8080 &>/dev/null &
  - phantomjs --webdriver=4444 > /dev/null &
  - cd profiles/contrib/lightning
  - sed -i -e 's/..\/..\//..\/..\/..\//g' behat.local.yml

script:
  - behat --strict

